/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RockPaperScissors;

public class App {

    /**
     * Juego de piedra papel o tijeras de 2 jugadores
     * 
     * Reglas:
     * 
     * Piedra gana a Tijeras
     * Papel gana a Piedra
     * Tijeras gana a Papel
     * (Tijeras le gana a mimi)
     * 
     * Output:
     * Al final del juego se debe de imprimir quien gano diciendo algo como
     * "El Jugador 1 Gano Piedra Rompe Tijeras" o
     * "El Jugador 2 Gano Tijers Rompe Papel" 
     * @return 
     */

    public static void Jankenpon(String jugador1, String jugador2){
        String piedra, papel, tijeras;
        piedra="piedra";
        papel="papel";
        tijeras="tijeras";
        if(!((jugador1==piedra||jugador1==papel||jugador1==tijeras)&&(jugador2==piedra||jugador2==papel||jugador2==tijeras))){
            System.out.println("Quien fue el puto?");
        }
        else if(jugador1==jugador2){
            System.out.println("empate");
        }
        else if((jugador1==piedra&&jugador2==tijeras)||(jugador1==papel&&jugador2==piedra)||(jugador1==tijeras&&jugador2==papel)){
            System.out.println("jugador 1 gana");
        }
        else{
            System.out.println("jugador 2 gana");
        }
        // if(jugador1==piedra){
        //     if(jugador2==piedra){
        //         System.out.println("empate");
        //     }
        //     else if(jugador2==papel){
        //         System.out.println("gana jugador 2");
        //     }
        //     else if(jugador2==tijeras){
        //         System.out.println("gana jugador 1");
        //     }
        //     else{
        //         System.out.println("putito");
        //     }
        // }
        // else if(jugador1==papel){
        //     if(jugador2==piedra){
        //         System.out.println("gana jugador 1");
        //     }
        //     else if(jugador2==papel){
        //         System.out.println("empate");
        //     }
        //     else if(jugador2==tijeras){
        //         System.out.println("gana jugador 2");
        //     }
        //     else{
        //         System.out.println("putito");
        //     }
        // }
        // else if(jugador1==tijeras){
        //     if(jugador2==piedra){
        //         System.out.println("gana jugador 2");
        //     }
        //     else if(jugador2==papel){
        //         System.out.println("gana jugador 1");
        //     }
        //     else if(jugador2==tijeras){
        //         System.out.println("empate");
        //     }
        //     else{
        //         System.out.println("putito");
        //     }
        // }
        // else{
        //     if(jugador2==tijeras||jugador2==papel||jugador2==piedra){
        //         System.out.println("jugador 1 es putito");
        //     }
        //     else{
        //         System.out.println("los dos jugadores son putos");
        //     }
        // }
        

    //     if (jugador1==jugador2){
    //    jugador1=piedra;
    //    jugador2=piedra;
       
    //     }

        
    }

    public static void main(String[] args) {
       
      

        // del profe
        String jugador1="pistola";
        String jugador2="pallaso";
              //Asume que el jugador 2 escoge y
        Jankenpon(jugador1, jugador2);



    }
}
