/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Java_Study;

public class App {

    /**
     * Haz una funcion que imprima la calificacion gringa de una array
     * con calificaciones
     * 
     * Si hay una calificacion fuera del rango imprime un mensaje diciendo que algo
     * anda mal
     * 
     * Rango 0 - 100
     * 
     * int A_Score = 90;
     * int B_Score = 80;
     * int C_Score = 70;
     * int D_Score = 60;
     * int MAX_Score = 100;
     * int MIN_Score = 0;
     * 
     * @param j
     * @return
     */
    public static void Califica(double[] calificacion) {
        for (int i = 0; i < calificacion.length; i++) {
            if (calificacion[i] < 60) {
                System.out.println("Persona "+(i+1)+" saca : F");
            } 
            else if (calificacion[i] < 70) {
                System.out.println("Persona "+(i+1)+" saca : D");
            } 
            else if (calificacion[i] < 80) {
                System.out.println("Persona "+(i+1)+" saca : C");
            } 
            else if (calificacion[i] < 90) {
                System.out.println("Persona "+(i+1)+" saca : B");
            } 
            else if (calificacion[i] <= 100) {
                System.out.println("Persona "+(i+1)+" saca : A");
            } 
            else {
                System.out.println("Persona "+(i+1)+" reprobado por gracioso");
            }
        }
    }

    /***
     * Busca las calificaciones que resultaron en un rango especifico
     * 
     * int A_Range = 90 - 100;
     * int B_Range = 80 - <90;
     * int C_Range = 70 - <80;
     * int D_Range = 60 - <70;
     * int F_Range = 0 - <60;
     * 
     * Ex:
     * 
     * calificacion = {10,20,30,40,50,60,65,68,70,80,90,100}
     * rango = "D"
     * 
     * Imprime:
     * 60,65,68
     * 
     * @param calificacion un array de calificaciones
     * @param rango        el rango 
     */
    public static void BuscaCalificiones(double[] calificacion,String rango) {
        
        for (int i = 0; i < calificacion.length; i++) {
            if (calificacion[i] >= 0&&calificacion[i]<60 &&rango.equals("F")) {
                System.out.println("Persona "+(i+1)+" sacaron : "+calificacion[i]);
            } 
            else if (calificacion[i] >= 60&&calificacion[i]<70 &&rango.equals("D")) {
                System.out.println("Persona "+(i+1)+" sacaron : "+calificacion[i]);
            } 
            else if (calificacion[i] >= 70&&calificacion[i]<80 &&rango.equals("C")) {
                System.out.println("Persona "+(i+1)+" sacaron : "+calificacion[i]);
            } 
            else if (calificacion[i] >= 80&&calificacion[i]<90 &&rango.equals("B")) {
                System.out.println("Persona "+(i+1)+" sacaron : "+calificacion[i]);
            }
            else if (calificacion[i] >= 90&&calificacion[i]<=100 &&rango.equals("A")) {
                System.out.println("Persona "+(i+1)+" sacaron : "+calificacion[i]);
            } 
        }
    }
     public static double[] fillArray(int n){
         double[] array = new double[n];
         for(int i=0;i<array.length;i++){
            array[i]=i;
        }
         return array;
     }   

     public static void printArray(double[] array){
         final int x=10;
         for(int i=0;i<array.length;i++){
             System.out.print(array[i]+"");
             if(i % x == x-1)System.out.println("");
         }
         System.out.println("");
     }
    public static void main(String[] args) {
        // Califica(grades);
        // BuscaCalificiones(grades,"C");
        int size = 101;
        double[] grades = fillArray(size);
        BuscaCalificiones(grades,"A");


    }
}
