/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Java_Study;

public class App {

    /**
     * Haz una funcion que imprima la calificacion gringa de una array
     * con calificaciones
     * 
     * Si hay una calificacion fuera del rango imprime un mensaje diciendo que algo
     * anda mal
     * 
     * Rango 0 - 100
     * 
     * int A_Score = 90;
     * int B_Score = 80;
     * int C_Score = 70;
     * int D_Score = 60;
     * int MAX_Score = 100;
     * int MIN_Score = 0;
     * 
     * @param j
     * @return
     */
    public static void Califica(double[] calificacion) {
        for (int i = 0; i < calificacion.length; i++) {
            if (calificacion[i] < 60) {
                System.out.println("F");
            } 
            else if (calificacion[i] < 70) {
                System.out.println("D");
            } 
            else if (calificacion[i] < 80) {
                System.out.println("C");
            } 
            else if (calificacion[i] < 90) {
                System.out.println("B");
            } 
            else if (calificacion[i] <= 100) {
                System.out.println("A");
            } 
            else {
                System.out.println("reprobado por gracioso");
            }
        }
    }

    public static void main(String[] args) {
        double[] grades = { 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 200 };
        Califica(grades);

    }
}
