/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cocacola;

import cocacola.classes.Coca;
import cocacola.classes.Persona;

public class App {
    
    

    public static void main(String[] args) {
        // Lata lata= new Lata(10,20,30);
        // System.out.println(lata.getHeight());
        // System.out.print(lata.getLength());
        // System.out.println(lata.getWidth());

        //con la coca
        // Coca coca = new Coca(10, 20, 30, 0);

        // System.out.println("cantidad: "+coca.getCantidad());
        // coca.llenar(355);

        // System.out.println("cantidad: "+coca.getCantidad());

        // coca.beber(15);
        // System.out.println("cantidad: "+coca.getCantidad());

        // System.out.println("Height: "+coca.getHeight());

        // coca.test();
        // System.out.println("Height: "+coca.getHeight());

        // System.out.println("Length: "+coca.getLength());

        // System.out.println("Width: "+coca.getWidth());

        // System.out.println("Volumen: "+coca.volumen());

        // personas
        int size=4;

        Persona[] personas = new Persona [size];
        String[] nombres = new String[] {"Zent","Mimi","Comunix","Cuervo"};

        // System.out.println(nombres[0]);     //empieza en 0
        // System.out.println(nombres[1]);
        // System.out.println(nombres[2]);
        // System.out.println(nombres[3]);
        // System.out.println(nombres[4]);      //error

        //== Compara por valor y direccion 
        //.equals() compara por valor

        //if Siempre va a checar si el caso es verdad o false
        //else if solo checara si los casos anteriores son falsos
        //else el ultimo caso que pasara siempre solo si los anteriores son falsos

        for(int i=0;i<size;i++) {
            if(nombres[i].equals("Comunix")) personas[i]=new Persona(nombres[i], new Coca(1, 2, 3, 150));
            else if(nombres[i].equals("Mimi")) personas[i]=new Persona(nombres[i], new Coca(1, 2, 3, 3000));
            else personas[i]=new Persona(nombres[i], new Coca(4, 5, 6, 355));

            System.out.println(personas[i].getNombre());
            System.out.println(personas[i].getCoca());
            personas[i].ImprimirCoca();
        }

        //personas que comparten coca
        System.out.println("con Coca compartida");
        int size2=2;
        Persona[] personas2 = new Persona[size2];
        String[] nombres2 = new String[] {"Mimi","suegrita"};

        Coca cocaCompartida = new Coca( 10,10,10, 1000);
        
        for (int i=0;i<size2;i++) {
            personas2[i]=new Persona(nombres2[i], cocaCompartida);
            System.out.println(personas2[i].getNombre());
            System.out.println(personas2[i].getCoca());
        }


    }

    public Object getGreeting() {
        return null;
    }
}
