/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Calculadora;

public class App {
 
  public static void imprimir (double[] array){
    for (double x:array){
      System.out.println(x+" ");
    }
    System.out.println("\n");
  }
  public static void imprimir (int[] array){
    for (int x:array){
      System.out.println(x+" ");
    }
    System.out.println("\n");
  }
  public static void imprimir (String val){
    System.out.println(val+" ");
  }

public static void main(String[] args) {
    Calculadora calculadora = new Calculadora();
    
    
    double restota=calculadora.Resta(100,2,3,4,5,6);
    System.out.println("\nresta de los valores:"+restota);

    double por=calculadora.Mul(100,2,3,4,5,6);
    System.out.println("\nmultiplicación de los valores:"+por);

    double divi=calculadora.Div(100,2,3,4,5,6);
    System.out.println("\ndivición de los valores:"+divi);

    int[] arrayint={123,234,453,7,456,567};

    // double sumota=calculadora.Suma(array); 
    // System.out.println("\nsuma de valores:"+sumota);

    // double max=calculadora.Max(array);
    // System.out.println("\nEl valor maximo de los valores:"+max);
    
    // double min=calculadora.Min(array);
    // System.out.println("\nEl valor minimo de los valores:"+min);

    // // ya entiendo profesor
    // System.out.println("\nOrden de menor a mayor:");
    // double orden1[]=calculadora.Ordenar(true, array);
    // imprimir(orden1);
    
    // System.out.println("\nOrden de mayor a menor:");
    // double orden2[]=calculadora.Ordenar(false, array);
    // imprimir(orden2);
    
    // System.out.println("\nOrden invertido:");
    // double inverter[]=calculadora.Invertir(array);
    // imprimir(inverter);

    // System.out.println("\nPromedio:");
    // double promedio=calculadora.Avg(array);
    // imprimir(promedio);

    System.out.println("buscar un valor en un array");
    int posicion=calculadora.findVal(7, arrayint);
    imprimir("valor: "+arrayint[posicion]);
    imprimir("posicion: "+posicion);

    int[] jaja=calculadora.Multiples(5, 10);
    System.out.println("\ntablita de multiplicar: ");
    imprimir(jaja);

    int[] cut=calculadora.cutArray(2, 6, jaja);
    System.out.println("cortalas pa siempre:");
    imprimir(cut);
  }
}
