/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Java_Study;

public class App {

    /**
     * Haz una funcion que imprima la calificacion gringa de una array
     * con calificaciones con sus respectivos nombres
     * 
     * Si hay una calificacion fuera del rango imprime un mensaje diciendo que algo
     * anda mal
     * 
     * Rango 0 - 100
     * 
     * int A_Score = 90;
     * int B_Score = 80;
     * int C_Score = 70;
     * int D_Score = 60;
     * int MAX_Score = 100;
     * int MIN_Score = 0;
     * 
     * el nombre de la nombres[i] n responde a la calificacion de la posicion n 
     * 
     * @param nombres       una array de strings que contiene todos los nombres de los estudiantes
     * @param calificacion  una array de doubles con las calificaiones de los estudiantes
     * @return
     */
    public static void Califica(String[] nombres,double[] calificacion) {
        for (int i = 0; i < calificacion.length; i++) {
            // for(int j=0;j<nombres.length;j++){
                
            // }
            if (calificacion[i] < 6.0) {
                System.out.println(nombres[i]  + " saca : F");
            } else if (calificacion[i] < 7.0) {
                System.out.println(nombres[i]  + " saca : D");
            } else if (calificacion[i] < 8.0) {
                System.out.println(nombres[i]  + " saca : C");
            } else if (calificacion[i] < 9.0) {
                System.out.println(nombres[i]  + " saca : B");
            } else if (calificacion[i] <= 10.0) {
                System.out.println(nombres[i]  + " saca : A");
            } else {
                System.out.println(nombres[i]  + " reprobado por gracioso");
            }
        }
    }

    /***
     * Busca las calificaciones que resultaron en un rango especifico
     * 
     * int A_Range = 90 - 100;
     * int B_Range = 80 - <90;
     * int C_Range = 70 - <80;
     * int D_Range = 60 - <70;
     * int F_Range = 0 - <60;
     * 
     * Ex:
     * 
     * calificacion = {10,20,30,40,50,60,65,68,70,80,90,100}
     * rango = "D"
     * 
     * Imprime:
     * 60,65,68
     * 
     * @param nombres       un array con los nombres de los estudiantes
     * @param calificacion  un array de calificaciones
     * @param rango         el rango
     */
    public static void BuscaCalificiones(String[] nombres, double[] calificacion, String rango) {
        for (int i = 0; i < calificacion.length; i++) {
            if (calificacion[i] >= 0 && calificacion[i] < 6.0 && rango.equals("F")) {
                System.out.println(nombres[i]  + " sacaron : " + calificacion[i]);
            } else if (calificacion[i] >= 60 && calificacion[i] < 7.0 && rango.equals("D")) {
                System.out.println(nombres[i]  + " sacaron : " + calificacion[i]);
            } else if (calificacion[i] >= 70 && calificacion[i] < 8.0 && rango.equals("C")) {
                System.out.println(nombres[i]  + " sacaron : " + calificacion[i]);
            } else if (calificacion[i] >= 80 && calificacion[i] < 9.0 && rango.equals("B")) {
                System.out.println(nombres[i]  + " sacaron : " + calificacion[i]);
            } else if (calificacion[i] >= 90 && calificacion[i] <= 10.0 && rango.equals("A")) {
                System.out.println(nombres[i]  + " sacaron : " + calificacion[i]);
            }
        }
    }

    // Llena una array con size n
    public static double[] fillArray(int n) {
        double[] array = new double[n]; // Crea una array de tamaño n
        for (int i = 0; i < array.length; i++) { // Ve desde el inicio de la array (i=0) hasta el final de la array
                                                 // (array.length)
            array[i] = i; // Ponle un valor en la posicion i

            // Numeros aleatorios
            // array[i] = (int)(Math.random()*10000); //Numero con 1-3 digitos y 2 decimales
            // array[i] /= 100; //Combiertelo en decimal
        }
        return array; // Siempre regresa lo que quieras no seas MIMI
    }

    // Imprimir un array
    public static void printArray(double[] array) {
        final int x = 10;
        for (int i = 0; i < array.length; i++) { // Ve desde el inicio de la array (i=0) hasta el final de la array
                                                 // (array.length)
            System.out.print(array[i] + " "); // Imprime el valor que se contiene en la posicion i
            if (i % x == x - 1)
                System.out.println(""); // Pon un final de linea cada x cantidad
        }
        System.out.println("");
    }

    public static void main(String[] args) {
        int size = 10;
        double[] grades = fillArray(size);
        String[] nombres= {"Mimi","Mato","a","Santiago","Ya","Que","No","Lo","Cuido", "XD"};


        printArray(grades);

        Califica(nombres,grades);
        BuscaCalificiones(nombres,grades, "F");

    }
}
