/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ayuda;

public class App {
   
    public static int max (int[] array){
        int max=array[0];                       //asume que el primer valor es el mayor
        for (int i=1;i<array.length;i++){
            //esto es lo mismo       
            max=((max<array[i])?array[i]:max);
                                                //(condicion)? verdad : falso
                                                //solo se va acceder a verdad i falso dependiendo de la condicion
                                                //if (condicion)
                                                //false
                                                //else
            //que esto                          //falso
            // if (max<array[i]){
            //     max=array[i];
            // }
            // else{
            //     max=max;
            // }
        }
        return max;
    }

    public static int min (int[] array){
        int min=array[0];
        for (int i=0;i<array.length;i++){
            min=((min>array[i])?array[i]:min);
        }
        return min;
    }

    // Primera iteracion del segundo for loop

        // i=0, j=1
        // {1 ,2 ,3 ,4 ,5 ,6}
        // 1 < 2 

        // i=0, j=2
        // {2 ,1 ,3 ,4 ,5 ,6}
        // 2 < 3 

        // i=0, j=3
        // {3 ,1 ,2 ,4 ,5 ,6}
        // 3 < 4 

        // i=0, j=4
        // {4 ,1 ,2 ,3 ,5 ,6}
        // 4 < 5 

        // i=0, j=5
        // {5 ,1 ,2 ,3 ,4 ,6}
        // 5 < 6

        // Al final
        // {6 ,1 ,2 ,3 ,4 ,5}

    
    public static int[] ordenar (int[] array, boolean asc){

        int[] arraytemp =new int[array.length];

        for (int i=0;i<array.length;i++){
            arraytemp[i] = array[i];
        }

        for(int i=0;i<arraytemp.length-1;i++){
            for(int j=i+1;j<arraytemp.length;j++){
                if(!asc&&arraytemp[i]<arraytemp[j]){
                    int temp = arraytemp[i];
                    arraytemp[i]=arraytemp[j];
                    arraytemp[j]=temp;
                }
                else if(asc&&arraytemp[i]>arraytemp[j]){
                    int temp = arraytemp[i];
                    arraytemp[i]=arraytemp[j];
                    arraytemp[j]=temp;
                }
            }
        }
        return arraytemp;
    }

    // public static int[] acendiente (int[] array, boolean asc){

    //     int[] arraytemp =new int[array.length];

    //     for (int i=0;i<array.length;i++){
    //         arraytemp[i] = array[i];
    //     }

    //     for(int i=0;i<arraytemp.length-1;i++){
    //         for(int j=i+1;j<arraytemp.length;j++){
    //             if(arraytemp[i]>arraytemp[j]){
    //                 int temp = arraytemp[i];
    //                 arraytemp[i]=arraytemp[j];
    //                 arraytemp[j]=temp;
    //             }
    //         }
    //     }
    //     return arraytemp;
    // }

    public static int[] invertir (int[] array){
        int[] arraytemp =new int[array.length];

        for (int i=0,j=array.length-1;i<array.length;i++,j--){
            arraytemp[i] = array[j];
        }
        // for(int i=0;i<array.length;i++){
        //     int temp = arraytemp[i];
        //             arraytemp[i]=arraytemp[j];
        //             arraytemp[j]=temp;
        // }

        return arraytemp;
    }

    public static void imprimir (int[] array){
        for(int x:array){
            System.out.print(x+" ");
        } 
        System.out.println("\n");  
    }

    public static void imprimir (int val){
        System.out.println(val+" ");
    }
    public static void main(String[] args) {
        
        int[] array = {123,245,456,3,567,678,789};

        System.out.println("La lista inicial");
        imprimir(array);
        //Esto (lo preferible)
        System.out.println("valor maximo");
        int max=max(array);
        imprimir(max);

        //es casi lo mismo que esto

        System.out.println("valor minimo");
        int min = min(array);
        imprimir(min);

       System.out.println("ordenar de mayor a menor");
       int[] array2 = ordenar(array, false);
       imprimir(array2);

       //segundo orden
       System.out.println("ordenar de menor a mayor");
       int[] array4 = ordenar(array, true);
       imprimir(array4);
    //    System.out.println("ordenar de menor a mayor");
    //    int[] array4 = acendiente(array, true);
    //    imprimir(array4);

       System.out.println("invertir");
       int[] array3 = invertir(array);
       imprimir(array3);

       System.out.println("La lista inicial");
        imprimir(array);
    }
}
